name: Build
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3.1.0
            - name: Install Go
              uses: actions/setup-go@v3.3.1
              with:
                go-version-file: go.mod
            - name: Build
              run: make build
