name: Docker build and push on tag
on:
  push:
    tags:
      - 'v*'
env:
  DOCKER_REPO: quay.io/costoolkit/elemental-cli
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.8.0
      - name: Export tag
        id: export_tag
        run: |
          echo "Using tag $(git describe --tags `git rev-list --tags --max-count=1`  2>/dev/null || echo 'v0.0.1')"
          TAG=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.1")
          echo "elemental_tag=$TAG" >> $GITHUB_OUTPUT
      - name: Docker meta for tag
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            ${{ env.DOCKER_REPO }}
          tags: |
            type=semver,pattern=v{{version}}
            type=raw,value=latest
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to Quay
        uses: docker/login-action@v2.1.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Push image  # should be a free build as everything has been cached and loaded
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # cache into GitHub actions cache, nice
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: elemental
          build-args: |
            ELEMENTAL_VERSION=${{ steps.export_tag.outputs.elemental_tag }}
            ELEMENTAL_COMMIT=${{ github.sha }}
      - name: Sign image
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign sign -y ${{ env.DOCKER_REPO }}:latest
          
          cosign sign -y ${{ env.DOCKER_REPO }}:${{ steps.export_tag.outputs.elemental_tag }}
