name: Lint
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3.1.0
            - name: Install Go
              uses: actions/setup-go@v3.3.1
              with:
                go-version-file: go.mod
            - name: Analysis
              uses: golangci/golangci-lint-action@v3
              with:
                args: -v
