name: Test
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3.1.0
              with:
                fetch-depth: 0
            - name: Check if only Dockerfile has changed
              id: changed-docker-files
              uses: tj-actions/changed-files@v33
              with:
                files: |
                    Dockerfile
                    .github/workflows/docker.yaml
            - name: Install Go
              if: steps.changed-docker-files.outputs.only_changed == 'false'
              uses: actions/setup-go@v3.3.1
              with:
                go-version-file: go.mod
            - name: Deps
              if: steps.changed-docker-files.outputs.only_changed == 'false'
              run: make test_deps
            - name: Run tests
              if: steps.changed-docker-files.outputs.only_changed == 'false'
              run: |
                make test
                sudo env PATH="$PATH" make test_root
            - name: Merge coverage
              if: steps.changed-docker-files.outputs.only_changed == 'false'
              run: |
                echo "mode: atomic" > coverage.out
                grep -v "mode: atomic" coverage.txt >> coverage.out
                grep -v "mode: atomic" coverage_root.txt >> coverage.out
            - name: Codecov
              if: steps.changed-docker-files.outputs.only_changed == 'false'
              uses: codecov/codecov-action@v3.1.1
              with:
                file: ./coverage.out
